### ISSUE TITLE
Program fails to download osu!taiko packs below 270

### ISSUE THREAD

**Issue by EikkieShaquille** [Saltssaumure/AutoBeatPack#2] opened 2024-07-11 11:48 UTC
![image](https://github.com/Osumatic/AutoBeatPack/assets/84169146/3beb7edf-f980-4bfe-bbf5-7ba60975c247)

**Comment by Saltssaumure** [comment] 2024-07-22 00:49
Issue caused by only getting the first page of beatmap packs, now fixed.

**Closed as completed** 2024-07-22 00:49 UTC
